// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clearinghouse_uploads.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countClearinghouseUploads = `-- name: CountClearinghouseUploads :one
SELECT COUNT(*)::bigint
FROM clearinghouse_uploads
WHERE $1::text IS NULL OR org_id = $1::text
`

func (q *Queries) CountClearinghouseUploads(ctx context.Context, orgID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countClearinghouseUploads, orgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createClearinghouseUpload = `-- name: CreateClearinghouseUpload :one
INSERT INTO clearinghouse_uploads (
    uuid,
    org_id,
    account_id,
    vulnerability_count,
    status,
    error_message
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING uuid, created_at, org_id, account_id, vulnerability_count, status, error_message
`

type CreateClearinghouseUploadParams struct {
	Uuid               uuid.UUID `json:"uuid"`
	OrgID              string    `json:"org_id"`
	AccountID          *string   `json:"account_id"`
	VulnerabilityCount *int32    `json:"vulnerability_count"`
	Status             string    `json:"status"`
	ErrorMessage       *string   `json:"error_message"`
}

func (q *Queries) CreateClearinghouseUpload(ctx context.Context, arg CreateClearinghouseUploadParams) (ClearinghouseUpload, error) {
	row := q.db.QueryRow(ctx, createClearinghouseUpload,
		arg.Uuid,
		arg.OrgID,
		arg.AccountID,
		arg.VulnerabilityCount,
		arg.Status,
		arg.ErrorMessage,
	)
	var i ClearinghouseUpload
	err := row.Scan(
		&i.Uuid,
		&i.CreatedAt,
		&i.OrgID,
		&i.AccountID,
		&i.VulnerabilityCount,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const createClearinghouseUploadFile = `-- name: CreateClearinghouseUploadFile :one
INSERT INTO clearinghouse_upload_files (
    uuid,
    clearinghouse_upload_uuid,
    filename,
    filepath
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING uuid, clearinghouse_upload_uuid, filename, filepath
`

type CreateClearinghouseUploadFileParams struct {
	Uuid                    uuid.UUID `json:"uuid"`
	ClearinghouseUploadUuid uuid.UUID `json:"clearinghouse_upload_uuid"`
	Filename                string    `json:"filename"`
	Filepath                string    `json:"filepath"`
}

func (q *Queries) CreateClearinghouseUploadFile(ctx context.Context, arg CreateClearinghouseUploadFileParams) (ClearinghouseUploadFile, error) {
	row := q.db.QueryRow(ctx, createClearinghouseUploadFile,
		arg.Uuid,
		arg.ClearinghouseUploadUuid,
		arg.Filename,
		arg.Filepath,
	)
	var i ClearinghouseUploadFile
	err := row.Scan(
		&i.Uuid,
		&i.ClearinghouseUploadUuid,
		&i.Filename,
		&i.Filepath,
	)
	return i, err
}

const getClearinghouseUpload = `-- name: GetClearinghouseUpload :one
SELECT uuid, created_at, org_id, account_id, vulnerability_count, status, error_message
FROM clearinghouse_uploads
WHERE uuid = $1
`

func (q *Queries) GetClearinghouseUpload(ctx context.Context, argUuid uuid.UUID) (ClearinghouseUpload, error) {
	row := q.db.QueryRow(ctx, getClearinghouseUpload, argUuid)
	var i ClearinghouseUpload
	err := row.Scan(
		&i.Uuid,
		&i.CreatedAt,
		&i.OrgID,
		&i.AccountID,
		&i.VulnerabilityCount,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const getClearinghouseUploadFileByName = `-- name: GetClearinghouseUploadFileByName :one
SELECT uuid, clearinghouse_upload_uuid, filename, filepath
FROM clearinghouse_upload_files
WHERE clearinghouse_upload_uuid = $1
    AND filename = $2
`

type GetClearinghouseUploadFileByNameParams struct {
	ClearinghouseUploadUuid uuid.UUID `json:"clearinghouse_upload_uuid"`
	Filename                string    `json:"filename"`
}

func (q *Queries) GetClearinghouseUploadFileByName(ctx context.Context, arg GetClearinghouseUploadFileByNameParams) (ClearinghouseUploadFile, error) {
	row := q.db.QueryRow(ctx, getClearinghouseUploadFileByName, arg.ClearinghouseUploadUuid, arg.Filename)
	var i ClearinghouseUploadFile
	err := row.Scan(
		&i.Uuid,
		&i.ClearinghouseUploadUuid,
		&i.Filename,
		&i.Filepath,
	)
	return i, err
}

const listClearinghouseUploadFiles = `-- name: ListClearinghouseUploadFiles :many
SELECT uuid, clearinghouse_upload_uuid, filename, filepath
FROM clearinghouse_upload_files
WHERE clearinghouse_upload_uuid = $1
ORDER BY filename
`

func (q *Queries) ListClearinghouseUploadFiles(ctx context.Context, clearinghouseUploadUuid uuid.UUID) ([]ClearinghouseUploadFile, error) {
	rows, err := q.db.Query(ctx, listClearinghouseUploadFiles, clearinghouseUploadUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearinghouseUploadFile{}
	for rows.Next() {
		var i ClearinghouseUploadFile
		if err := rows.Scan(
			&i.Uuid,
			&i.ClearinghouseUploadUuid,
			&i.Filename,
			&i.Filepath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClearinghouseUploadFilesByUploads = `-- name: ListClearinghouseUploadFilesByUploads :many
SELECT uuid, clearinghouse_upload_uuid, filename, filepath
FROM clearinghouse_upload_files
WHERE clearinghouse_upload_uuid = ANY($1::uuid[])
ORDER BY clearinghouse_upload_uuid, filename
`

func (q *Queries) ListClearinghouseUploadFilesByUploads(ctx context.Context, uploadUuids []uuid.UUID) ([]ClearinghouseUploadFile, error) {
	rows, err := q.db.Query(ctx, listClearinghouseUploadFilesByUploads, uploadUuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearinghouseUploadFile{}
	for rows.Next() {
		var i ClearinghouseUploadFile
		if err := rows.Scan(
			&i.Uuid,
			&i.ClearinghouseUploadUuid,
			&i.Filename,
			&i.Filepath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClearinghouseUploads = `-- name: ListClearinghouseUploads :many
SELECT uuid, created_at, org_id, account_id, vulnerability_count, status, error_message
FROM clearinghouse_uploads
WHERE $1::text IS NULL OR org_id = $1::text
ORDER BY created_at DESC, uuid DESC
LIMIT $3 OFFSET $2
`

type ListClearinghouseUploadsParams struct {
	OrgID      *string `json:"org_id"`
	PageOffset int32   `json:"page_offset"`
	PageLimit  int32   `json:"page_limit"`
}

func (q *Queries) ListClearinghouseUploads(ctx context.Context, arg ListClearinghouseUploadsParams) ([]ClearinghouseUpload, error) {
	rows, err := q.db.Query(ctx, listClearinghouseUploads, arg.OrgID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearinghouseUpload{}
	for rows.Next() {
		var i ClearinghouseUpload
		if err := rows.Scan(
			&i.Uuid,
			&i.CreatedAt,
			&i.OrgID,
			&i.AccountID,
			&i.VulnerabilityCount,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
